# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Dependabot configuration file

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"  # Location of package.json file(s)
    schedule:
      interval: "daily"  # Update frequency: "daily" for frequent updates
    commit-message:
      prefix: "chore(deps): "  # Prefix for commit messages
    labels:
      - "dependencies"  # Label for pull requests
    ignore:
      - dependency-name: "eslint"  # Ignore specific dependencies from being updated
    versioning-strategy: "lockfile-only"  # Versioning strategy: "lockfile-only" to use lockfile versions

