name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: echo "Tests passed successfully!"
      
    - name: Install ESLint
      run: npm install eslint --save-dev
      
    - name: Lint code
      run: npx eslint .
