name: Performance Metrics

on:
  push:
    branches:
      - main

jobs:
  analyze_performance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Measure linting performance
      run: |
        time npx eslint . --config .eslintrc

